#!/usr/bin/env sh
# Tag a release, refusing when the release would hit the 403.
#
# dist's host job creates the release with `gh release create --target <sha>`.
# Supplying target_commitish makes GitHub demand `workflows: write` on top of
# `contents: write` whenever the commit range being released touches
# `.github/workflows/**` -- and GITHUB_TOKEN cannot hold that scope at all.
# The result is `HTTP 403: Resource not accessible by integration` from a job
# whose own log says `Contents: write`, which is about as misleading as an
# error gets. Three releases were assembled by hand before it was understood.
#
# `release.yml` is generated by dist and `dist host` verifies the file against
# what it would generate, so the flag cannot simply be removed. What is left is
# keeping the commit range empty, which this enforces rather than trusts.
#
#   scripts/tag-release.sh v0.3.0

set -eu

tag=${1:-}
if [ -z "$tag" ]; then
    echo "usage: $0 vX.Y.Z" >&2
    exit 2
fi
case "$tag" in
    v*) ;;
    *) echo "error: a release tag starts with v, got '$tag'" >&2; exit 2 ;;
esac

git fetch --quiet origin

head=$(git rev-parse HEAD)
remote=$(git rev-parse origin/main)

if [ "$head" != "$remote" ]; then
    echo "error: HEAD is not origin/main." >&2
    echo "  HEAD        $head" >&2
    echo "  origin/main $remote" >&2
    echo "Push first, and let CI go green, before tagging." >&2
    exit 1
fi

if [ -n "$(git status --porcelain)" ]; then
    echo "error: the working tree is dirty; commit or stash first." >&2
    exit 1
fi

version=$(grep -m1 '^version = ' Cargo.toml | cut -d'"' -f2)
if [ "v$version" != "$tag" ]; then
    echo "error: Cargo.toml says $version, you asked for $tag." >&2
    exit 1
fi

echo "tagging $tag at $(git rev-parse --short HEAD)"
git tag -a "$tag" -m "ccred $version"
git push origin "$tag"

cat <<EOF

Pushed. Now do nothing to main until the run finishes:

    gh run watch --repo Zigecek/ccred

Any commit landing on main before the host job reaches `gh release create`
puts that commit in the released range. If it touches .github/workflows the
job dies with a 403 and the release has to be re-tagged at the new tip.
EOF
